blank_issues_enabled: false
contact_links:
  - name: WebBanao.new related issues
    url: https://github.com/stackblitz/webbanao.new/issues/new/choose
    about: Report issues related to WebBanao.new (not WebBanao.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other WebBanao.diy users.
